mkdir -p "./v1.1c"

cp -R ../Resources/data/stage/bg/bg2.tmx "./v1.1c"
cp -R ../Resources/data/stage/bg/bg3.tmx "./v1.1c"
cp -R ../Resources/data/stage/bg/bg4.tmx "./v1.1c"

cp -R ../Resources/data/stage/s11/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s12/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s13/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s14/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s15/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s16/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s17/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s18/*.tmx "./v1.1c"

cp -R ../Resources/data/stage/s21/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s22/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s23/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s24/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s25/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s26/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s27/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s28/*.tmx "./v1.1c"

cp -R ../Resources/data/stage/s31/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s32/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s33/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s34/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s35/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s36/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s37/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s38/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s39/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s310/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s311/*.tmx "./v1.1c"
cp -R ../Resources/data/stage/s312/*.tmx "./v1.1c"
